-- =============================================================================
-- Orders and reviews — the manual sales workflow
-- =============================================================================
-- Bondo does not take money online. A shopper fills a basket, leaves a phone
-- number, and a manager rings them back to agree the configuration, the delivery
-- and the price. That is how computer shops in Tashkent actually sell, and it is
-- the workflow this schema models — not a payment funnel with the payment step
-- removed (ADR-63).
--
-- Two consequences run through everything below:
--
--   * There is no payment state. `order_status` tracks a **conversation**, not a
--     transaction: someone rang, someone confirmed, someone shipped. A `paid`
--     status would be a field nobody updates, because the cash arrives at the
--     door.
--   * An order is placed by a phone number, not by an account. `user_id` is
--     nullable and guest checkout is the common path, so `phone` — not email —
--     is the required contact column.
--
-- -----------------------------------------------------------------------------
-- Nothing writes an order directly
-- -----------------------------------------------------------------------------
-- `place_order()` is the only way an order comes into existence, and neither
-- `anon` nor `authenticated` holds insert on `orders` or `order_items`. The
-- reason is not tidiness:
--
--   * **Prices are read from the database, never accepted from the caller.** A
--     checkout that trusts a client-supplied total is a checkout that sells a
--     laptop for one dollar. The function re-reads every price under the same
--     transaction that writes the row.
--   * **An order and its lines are one transaction.** With table-level inserts a
--     guest could write an `orders` row and then fail on the items, leaving an
--     order with nothing in it and a manager ringing about nothing.
--   * **A guest order cannot be attached to a stranger's items.** With
--     `user_id is null` on a public insert policy there is no ownership to check,
--     so any anonymous caller could append lines to any other guest's order. A
--     definer function has no such gap: it inserts both halves itself.
--
-- -----------------------------------------------------------------------------
-- Reviews are gated in the database, not in the action
-- -----------------------------------------------------------------------------
-- The rule is "only a verified buyer, only after delivery, once per product".
-- That is expressed as an RLS `with check` containing the join it depends on, so
-- the guarantee survives a Server Action written in a hurry two phases from now
-- (ADR-66).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Status vocabulary
-- -----------------------------------------------------------------------------
-- Seven values, each of which a manager can say out loud on the phone. They form
-- a pipeline rather than a state machine with branches: an order moves forward,
-- or it is cancelled. `cancelled` is reachable from anywhere and is terminal.
--
-- Deliberately **not** here: `paid`, `refunded`, `pending`. Those are payment
-- states and there is no payment. The interface vocabulary in `types/admin.ts`
-- carried them as a declared exception until this migration; it now derives from
-- this enum and the exception in `scripts/check-enums.mjs` is deleted.
create type public.order_status as enum (
  'new',
  'contacted',
  'confirmed',
  'preparing',
  'shipped',
  'delivered',
  'cancelled'
);

comment on type public.order_status is
  'The stage of the conversation with the customer. No payment states: Bondo settles at the door (ADR-63).';

-- -----------------------------------------------------------------------------
-- Order reference
-- -----------------------------------------------------------------------------
-- A human handle for a phone call: "BND-000148". A UUID is unreadable over the
-- phone and a random string collides; a sequence is neither.
--
-- Starting at 1000 so the first order is not obviously the first order — a
-- cosmetic choice, and the only one in this file.
create sequence public.order_reference_seq start with 1000;

comment on sequence public.order_reference_seq is
  'Feeds orders.reference. A sequence rather than a random string: it never collides and it can be read aloud.';

-- -----------------------------------------------------------------------------
-- orders
-- -----------------------------------------------------------------------------
create table public.orders (
  id uuid primary key default gen_random_uuid(),

  -- What the customer and the manager both say out loud. Unique, immutable, and
  -- generated by `place_order` rather than by the client.
  reference text not null unique,

  -- Null for a guest. Guest checkout is the common path, not an edge case: a
  -- shopper who has to register before phoning us has already left.
  user_id uuid references auth.users (id) on delete set null,

  status public.order_status not null default 'new',

  -- The language the order was placed in. This is operational, not decorative:
  -- the manager about to ring this number needs to know which language to open
  -- with, and `order_items.product_name` is snapshotted in it.
  locale public.locale not null default 'uz',

  -- ---------------------------------------------------------------------------
  -- Contact — the entire point of the flow
  -- ---------------------------------------------------------------------------
  customer_name text not null,
  -- Required, and the only required contact channel. Email is not collected at
  -- checkout at all: nobody in this market waits for an order confirmation
  -- email, and a field we never read is a field that rots.
  phone text not null,
  -- Optional second channel. Uzbek retail runs on Telegram, and a customer who
  -- gives one often prefers it to a call.
  telegram text,

  address text not null,
  city text,

  -- What the customer typed. Free text, shown to the manager verbatim.
  notes text,

  -- The operator's own notes. Never rendered on the storefront, and separated
  -- from `notes` so that "what they asked for" and "what we think" cannot be
  -- confused by whoever picks the order up next.
  internal_note text,

  -- ---------------------------------------------------------------------------
  -- Money — integer minor units throughout (ADR-2)
  -- ---------------------------------------------------------------------------
  -- Computed by `place_order` from live prices and then frozen. An order never
  -- re-reads a product's current price.
  subtotal_cents integer not null,
  -- Zero at capture and set by the manager on the call. Delivery in Tashkent is
  -- quoted per address, so a checkout that guessed it would be quoting a number
  -- the shop then has to walk back.
  delivery_fee_cents integer not null default 0,
  total_cents integer not null,
  -- Snapshotted alongside the amounts. The store currency is a setting and can
  -- change; an order priced before the change must keep the currency it was
  -- priced in, or the history silently re-denominates.
  currency text not null default 'USD',

  placed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users (id) on delete set null,

  constraint orders_reference_format check (reference ~ '^BND-[0-9]{6,}$'),
  constraint orders_customer_name_length check (
    char_length(customer_name) between 2 and 120
  ),
  -- Deliberately loose. Uzbek numbers are written +998 90 123 45 67, 909123456
  -- and every shape between; a strict pattern here would reject real customers
  -- to buy a tidiness nobody benefits from. The form normalises, this floor
  -- catches an empty box.
  constraint orders_phone_length check (char_length(phone) between 7 and 32),
  constraint orders_telegram_length check (
    telegram is null or char_length(telegram) between 2 and 64
  ),
  constraint orders_address_length check (char_length(address) between 5 and 500),
  constraint orders_city_length check (city is null or char_length(city) <= 120),
  constraint orders_notes_length check (notes is null or char_length(notes) <= 2000),
  constraint orders_internal_note_length check (
    internal_note is null or char_length(internal_note) <= 2000
  ),
  constraint orders_subtotal_non_negative check (subtotal_cents >= 0),
  constraint orders_delivery_fee_non_negative check (delivery_fee_cents >= 0),
  constraint orders_total_non_negative check (total_cents >= 0),
  -- The one arithmetic invariant worth enforcing at the table: a total that does
  -- not equal its parts is a bug that would otherwise surface as a customer
  -- being charged the wrong amount at the door.
  constraint orders_total_is_sum check (
    total_cents = subtotal_cents + delivery_fee_cents
  )
);

comment on table public.orders is
  'A manual sale. Captured online, agreed by phone, settled on delivery — there is no payment state (ADR-63).';

comment on column public.orders.locale is
  'The language the order was placed in. Tells the manager which language to ring in, and which language order_items.product_name is written in.';

comment on column public.orders.delivery_fee_cents is
  'Zero at capture; set by the operator once the address is agreed on the call.';

-- The admin list is "newest first", always. This index is what keeps that
-- ordering off a sequential scan once the table is large.
create index idx_orders_placed_at on public.orders (placed_at desc);

-- The list filters by status far more often than by anything else, and the
-- dashboard counts by it.
create index idx_orders_status on public.orders (status, placed_at desc);

-- A customer's own order history, and the join behind the review gate.
create index idx_orders_user_id on public.orders (user_id, placed_at desc)
  where user_id is not null;

-- Support looks an order up by the number the customer read out. Trigram rather
-- than btree because they misremember digits and search for a fragment.
create index idx_orders_reference_trgm on public.orders
  using gin (reference extensions.gin_trgm_ops);

-- The same lookup, by the number they rang from.
create index idx_orders_phone_trgm on public.orders
  using gin (phone extensions.gin_trgm_ops);

-- -----------------------------------------------------------------------------
-- order_items
-- -----------------------------------------------------------------------------
-- **Every commercially meaningful column here is a snapshot.** The roadmap has
-- required this since Phase 4 was written and the reason is worth restating: a
-- line that joins to `products` for its price shows a different total every time
-- the catalog is re-priced, and an order is a record of an agreement, not a live
-- query.
--
-- `product_id` survives as a **link**, not as a source of truth: it is what the
-- admin follows to open the product, and what the review gate joins on. It is
-- nullable and `on delete set null`, so deleting a product cannot delete the
-- history of having sold it.
create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,

  product_id uuid references public.products (id) on delete set null,
  variant_id uuid references public.product_variants (id) on delete set null,

  -- The name as the customer saw it, in `orders.locale`. Not localized into
  -- three columns: the order was placed in one language and that is the one the
  -- manager should read back over the phone.
  product_name text not null,
  sku text not null,

  unit_price_cents integer not null,
  quantity integer not null,
  line_total_cents integer not null,

  created_at timestamptz not null default now(),

  constraint order_items_product_name_length check (
    char_length(product_name) between 1 and 300
  ),
  constraint order_items_sku_length check (char_length(sku) between 1 and 64),
  constraint order_items_unit_price_non_negative check (unit_price_cents >= 0),
  constraint order_items_quantity_positive check (quantity > 0),
  -- A basket is not a wholesale channel. The cap turns a fat-fingered 99999 into
  -- a rejected insert rather than an order the shop cannot fill.
  constraint order_items_quantity_sane check (quantity <= 100),
  constraint order_items_line_total_is_product check (
    line_total_cents = unit_price_cents * quantity
  )
);

comment on table public.order_items is
  'One line of an order, with name, SKU and price snapshotted at capture. product_id is a link for the admin, never the source of the price.';

create index idx_order_items_order_id on public.order_items (order_id);

-- Drives the review gate's `exists`, and "who bought this product".
create index idx_order_items_product_id on public.order_items (product_id)
  where product_id is not null;

-- "Which orders included this configuration", and the index that keeps
-- `on delete set null` from scanning the table when a variant is retired.
create index idx_order_items_variant_id on public.order_items (variant_id)
  where variant_id is not null;

-- -----------------------------------------------------------------------------
-- order_status_history — the timeline
-- -----------------------------------------------------------------------------
-- Append-only, and written by a trigger rather than by the caller. Both choices
-- are the ones the inventory ledger already made (ADR-24, ADR-27) and for the
-- same reason: a history a caller has to remember to write is a history with
-- holes in it, and a history anyone can edit is not evidence of anything.
--
-- `changed_by_name` is denormalised deliberately, matching what
-- 20260807001000_audit_log_independence did to `audit_logs`: an operator who
-- leaves the company should not erase the record of who moved an order.
create table public.order_status_history (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,

  -- Null on the row the insert trigger writes: an order does not come from
  -- anywhere, it starts.
  from_status public.order_status,
  to_status public.order_status not null,

  note text,

  changed_by uuid references auth.users (id) on delete set null,
  changed_by_name text,

  created_at timestamptz not null default now(),

  constraint order_status_history_note_length check (
    note is null or char_length(note) <= 1000
  ),
  -- A transition to the status it already held is not a transition. Without this
  -- a double-clicked save button writes two identical timeline entries.
  constraint order_status_history_actually_changed check (
    from_status is null or from_status <> to_status
  )
);

comment on table public.order_status_history is
  'Append-only timeline of an order status. Written by a trigger, never by a caller, and immutable once written.';

create index idx_order_status_history_order_id
  on public.order_status_history (order_id, created_at desc);

-- "Everything this operator touched", and the index behind `on delete set null`
-- when their auth user is removed.
create index idx_order_status_history_changed_by
  on public.order_status_history (changed_by)
  where changed_by is not null;

create trigger order_status_history_append_only
  before update or delete on public.order_status_history
  for each row execute function public.reject_ledger_mutation();

-- -----------------------------------------------------------------------------
-- The trigger that writes the timeline
-- -----------------------------------------------------------------------------
-- Fires on insert (recording the birth of the order) and on any update that
-- actually moves the status. `security definer` because the row it writes is
-- append-only and the caller holds no insert on it — the timeline is the
-- database's record, not the application's.
create or replace function public.record_order_status_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_name text;
begin
  if tg_op = 'UPDATE' and new.status is not distinct from old.status then
    return new;
  end if;

  -- Resolved once, here, rather than joined at read time: see the table comment.
  select p.full_name into actor_name
  from public.profiles p
  where p.id = (select auth.uid());

  insert into public.order_status_history (
    order_id, from_status, to_status, changed_by, changed_by_name
  )
  values (
    new.id,
    case when tg_op = 'UPDATE' then old.status else null end,
    new.status,
    (select auth.uid()),
    actor_name
  );

  return new;
end;
$$;

comment on function public.record_order_status_change() is
  'AFTER INSERT/UPDATE on orders: appends a timeline row whenever the status actually moves.';

create trigger orders_record_status_change
  after insert or update of status on public.orders
  for each row execute function public.record_order_status_change();

create trigger orders_set_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- place_order — the only way an order is created
-- -----------------------------------------------------------------------------
-- Takes the basket as `[{ product_id, variant_id, quantity }]` and **no prices**.
-- Everything chargeable is read here, inside the same transaction that writes the
-- row, from the same tables the storefront renders from.
--
-- A variant's price wins over its product's when one is given, matching
-- ADR-62: once a variant exists it is the purchasable thing.
--
-- Raises rather than skipping when a line cannot be priced. A basket containing
-- something unbuyable is a basket the customer should be told about, not one
-- that quietly arrives at the shop one item short.
create or replace function public.place_order(
  p_customer_name text,
  p_phone text,
  p_address text,
  p_items jsonb,
  p_telegram text default null,
  p_city text default null,
  p_notes text default null,
  p_locale public.locale default 'uz'
)
returns public.orders
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_order public.orders;
  item jsonb;
  resolved_name text;
  resolved_sku text;
  resolved_price integer;
  line_quantity integer;
  running_subtotal integer := 0;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'an order needs at least one item'
      using errcode = 'check_violation';
  end if;

  -- A guard, not a business rule: 50 distinct lines is far past any real basket
  -- and well short of what would make this loop expensive.
  if jsonb_array_length(p_items) > 50 then
    raise exception 'too many lines in one order'
      using errcode = 'check_violation';
  end if;

  insert into public.orders (
    reference, user_id, locale,
    customer_name, phone, telegram, address, city, notes,
    subtotal_cents, total_cents
  )
  values (
    'BND-' || lpad(nextval('public.order_reference_seq')::text, 6, '0'),
    (select auth.uid()),
    p_locale,
    p_customer_name, p_phone, p_telegram, p_address, p_city, p_notes,
    0, 0
  )
  returning * into new_order;

  for item in select * from jsonb_array_elements(p_items)
  loop
    line_quantity := coalesce((item ->> 'quantity')::integer, 0);

    if line_quantity <= 0 then
      raise exception 'every line needs a positive quantity'
        using errcode = 'check_violation';
    end if;

    if (item ->> 'variant_id') is not null then
      -- A variant is only purchasable while it and its product are both
      -- visible. The predicate is the storefront's read policy restated: an
      -- order must not be placeable for something the shopper could not see.
      select
        coalesce(pt.name, pt_uz.name, p.sku),
        v.sku,
        coalesce(v.sale_price_cents, v.price_cents)
      into resolved_name, resolved_sku, resolved_price
      from public.product_variants v
      join public.products p on p.id = v.product_id
      left join public.product_translations pt
        on pt.product_id = p.id and pt.locale = p_locale
      left join public.product_translations pt_uz
        on pt_uz.product_id = p.id and pt_uz.locale = 'uz'
      where v.id = (item ->> 'variant_id')::uuid
        and v.deleted_at is null
        and v.is_active
        and p.deleted_at is null
        and p.status = 'active'
        and p.visibility = 'public'
        and p.published_at is not null
        and p.published_at <= now();
    else
      select
        coalesce(pt.name, pt_uz.name, p.sku),
        p.sku,
        coalesce(p.sale_price_cents, p.price_cents)
      into resolved_name, resolved_sku, resolved_price
      from public.products p
      left join public.product_translations pt
        on pt.product_id = p.id and pt.locale = p_locale
      left join public.product_translations pt_uz
        on pt_uz.product_id = p.id and pt_uz.locale = 'uz'
      where p.id = (item ->> 'product_id')::uuid
        and p.deleted_at is null
        and p.status = 'active'
        and p.visibility = 'public'
        and p.published_at is not null
        and p.published_at <= now();
    end if;

    if resolved_price is null then
      raise exception 'a product in this order is no longer available'
        using errcode = 'no_data_found';
    end if;

    insert into public.order_items (
      order_id, product_id, variant_id,
      product_name, sku, unit_price_cents, quantity, line_total_cents
    )
    values (
      new_order.id,
      (item ->> 'product_id')::uuid,
      (item ->> 'variant_id')::uuid,
      resolved_name, resolved_sku,
      resolved_price, line_quantity, resolved_price * line_quantity
    );

    running_subtotal := running_subtotal + resolved_price * line_quantity;
  end loop;

  update public.orders
  set subtotal_cents = running_subtotal,
      total_cents = running_subtotal + delivery_fee_cents
  where id = new_order.id
  returning * into new_order;

  return new_order;
end;
$$;

comment on function public.place_order(text, text, text, jsonb, text, text, text, public.locale) is
  'Creates an order and its lines in one transaction, pricing every line from the database. The only write path into orders — no role holds insert on the table.';

-- -----------------------------------------------------------------------------
-- product_reviews
-- -----------------------------------------------------------------------------
-- One review per buyer per product, and only after that buyer's order reached
-- `delivered`. `order_id` is on the row rather than merely checked at insert
-- time so the claim stays auditable: an admin looking at a review can see which
-- order earned it.
create table public.product_reviews (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  order_id uuid not null references public.orders (id) on delete cascade,

  rating smallint not null,
  title text,
  body text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint product_reviews_rating_range check (rating between 1 and 5),
  constraint product_reviews_title_length check (
    title is null or char_length(title) between 1 and 120
  ),
  constraint product_reviews_body_length check (
    body is null or char_length(body) between 1 and 2000
  ),
  -- The "one review per purchased product" half of the rule. The "verified
  -- buyer" half is the RLS policy below; this one is a constraint because it is
  -- an invariant of the data rather than a question about the caller.
  unique (user_id, product_id)
);

comment on table public.product_reviews is
  'A review from a verified buyer. The delivered-order requirement is enforced by RLS, not by the application (ADR-66).';

create index idx_product_reviews_product_id
  on public.product_reviews (product_id, created_at desc);

create index idx_product_reviews_user_id on public.product_reviews (user_id);

-- "Which reviews did this order earn", and the cascade's index.
create index idx_product_reviews_order_id on public.product_reviews (order_id);

create trigger product_reviews_set_updated_at
  before update on public.product_reviews
  for each row execute function public.set_updated_at();

-- =============================================================================
-- Permissions
-- =============================================================================
-- Two new keys. The admin module registry may not invent a permission (ADR-44),
-- so an Orders module needs the database to name what it offers first.
--
-- There is deliberately no `orders.delete`: an order is never deleted. A sale
-- that fell through is `cancelled`, which keeps the phone number, the basket and
-- the reason — all three of which the shop wants when the customer rings back.
insert into public.permissions (key, resource, action, description) values
  ('orders.read',   'orders', 'read',   'View orders and their timeline'),
  ('orders.update', 'orders', 'update', 'Change order status and add notes');

-- Repeats the set-based insert from 20260801000200 so super_admin picks up
-- anything added later without somebody having to remember.
insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
cross join public.permissions p
where r.key = 'super_admin'
  and p.key in ('orders.read', 'orders.update')
on conflict do nothing;

-- The support agent is the person who actually rings the customer, so this is
-- the role the whole workflow lives in. Its description said "Changes nothing",
-- which stops being true here and is corrected rather than left to mislead.
insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
cross join public.permissions p
where r.key = 'support_agent'
  and p.key in ('orders.read', 'orders.update')
on conflict do nothing;

update public.roles
set description = 'Handles orders: rings customers, moves status, reads the catalog.'
where key = 'support_agent';

-- A catalog manager needs to see what sold, and nothing more.
insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
cross join public.permissions p
where r.key = 'catalog_manager'
  and p.key = 'orders.read'
on conflict do nothing;

-- =============================================================================
-- Row Level Security
-- =============================================================================
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;
alter table public.product_reviews enable row level security;

-- -----------------------------------------------------------------------------
-- orders
-- -----------------------------------------------------------------------------
-- No insert policy for anyone. `place_order` is `security definer` and is the
-- only writer; adding one here would reopen every hole the function exists to
-- close.
--
-- No delete policy for anyone, including super admin. Cancelling is an update.
create policy "orders: a customer reads their own"
  on public.orders for select
  to authenticated
  using (user_id = (select auth.uid()));

create policy "orders: orders.read sees every order"
  on public.orders for select
  to authenticated
  using (public.has_permission('orders.read'));

create policy "orders: orders.update maintains them"
  on public.orders for update
  to authenticated
  using (public.has_permission('orders.update'))
  with check (public.has_permission('orders.update'));

-- -----------------------------------------------------------------------------
-- order_items
-- -----------------------------------------------------------------------------
-- Readable exactly when the parent order is. Written only by `place_order`.
create policy "order_items: readable with the order"
  on public.order_items for select
  to authenticated
  using (
    exists (
      select 1 from public.orders o
      where o.id = order_items.order_id
        and (o.user_id = (select auth.uid()) or public.has_permission('orders.read'))
    )
  );

-- -----------------------------------------------------------------------------
-- order_status_history
-- -----------------------------------------------------------------------------
-- A customer sees their own order move; that is the tracking page. Staff see
-- everything. Nobody writes — the trigger does, and the append-only guard
-- refuses updates and deletes even to `service_role`.
create policy "order_status_history: readable with the order"
  on public.order_status_history for select
  to authenticated
  using (
    exists (
      select 1 from public.orders o
      where o.id = order_status_history.order_id
        and (o.user_id = (select auth.uid()) or public.has_permission('orders.read'))
    )
  );

-- -----------------------------------------------------------------------------
-- product_reviews
-- -----------------------------------------------------------------------------
-- Reviews are public: a shopper who has not bought anything still reads them.
create policy "product_reviews: anyone reads reviews of published products"
  on public.product_reviews for select
  to anon, authenticated
  using (
    exists (
      select 1 from public.products p
      where p.id = product_reviews.product_id
        and p.deleted_at is null
        and p.status = 'active'
        and p.visibility = 'public'
        and p.published_at is not null
        and p.published_at <= now()
    )
  );

-- **This policy is the feature.** Everything the brief asks for — verified
-- buyer, delivered order, one per purchased product — is here, where a Server
-- Action cannot forget it and a leaked anon key cannot get round it.
create policy "product_reviews: a delivered buyer may review what they bought"
  on public.product_reviews for insert
  to authenticated
  with check (
    user_id = (select auth.uid())
    and exists (
      select 1
      from public.orders o
      join public.order_items oi on oi.order_id = o.id
      where o.id = product_reviews.order_id
        and o.user_id = (select auth.uid())
        and o.status = 'delivered'
        and oi.product_id = product_reviews.product_id
    )
  );

-- An author may correct their own wording. They may not move it to another
-- product or another order, which `with check` re-asserting the join prevents.
create policy "product_reviews: an author edits their own"
  on public.product_reviews for update
  to authenticated
  using (user_id = (select auth.uid()))
  with check (
    user_id = (select auth.uid())
    and exists (
      select 1
      from public.orders o
      join public.order_items oi on oi.order_id = o.id
      where o.id = product_reviews.order_id
        and o.user_id = (select auth.uid())
        and o.status = 'delivered'
        and oi.product_id = product_reviews.product_id
    )
  );

create policy "product_reviews: an author deletes their own"
  on public.product_reviews for delete
  to authenticated
  using (user_id = (select auth.uid()));

-- =============================================================================
-- Grants
-- =============================================================================
-- Explicit and least-privilege, matching 20260801000900 (ADR-30): a mistaken
-- policy still meets a closed second gate.
--
-- Note what `anon` gets: reviews, and the right to call `place_order`. It holds
-- no table privilege on `orders` or `order_items` at all, so a guest checkout
-- works and a guest cannot read back what anybody else ordered.
grant select on public.orders to authenticated;
grant update on public.orders to authenticated;
grant select on public.order_items to authenticated;
grant select on public.order_status_history to authenticated;

grant select on public.product_reviews to anon, authenticated;
grant insert, update, delete on public.product_reviews to authenticated;

grant execute on function public.place_order(
  text, text, text, jsonb, text, text, text, public.locale
) to anon, authenticated;

-- The sequence is driven from inside a definer function, so no client role needs
-- it. Stated rather than left implicit, because a missing sequence grant is a
-- classic silent checkout failure.
revoke all on sequence public.order_reference_seq from anon, authenticated;
